name: Quality Checks

on:
    push:
        branches: [main]

jobs:
  build:
    name: Run Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: global install
        run: npm ci

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            reporter: github-pr-review 
            eslint_flags: 'src/'

      - name: Typecheck
        run: npx tsc --noEmit


      
        
        



