name: Quality Checks

on: 
  push:
    branches: [main]

jobs:
  build:
    name: Run Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
            node-version: 23

      - name: global install
        run: npm install

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            reporter: github-pr-review 
            eslint_flags: 'src/'

      - name: Typecheck
        run: npx tsc --noEmit
    
      - name : Build Check
        run : npm run build
        env:
            NEXT_PUBLIC_PROJECT_ID: ${{ secrets.PROJECT_ID }}
            NEXT_PUBLIC_DATASET: ${{ secrets.DATASET }}
            APP_ID : ${{secrets.APP_ID}}
     
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
        



