name: Quality Checks

on: 
  push:
    branches: [main]

jobs:
  build:
    name: Run Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
            node-version: 23

      - name: global install
        run: npm install

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            reporter: github-pr-review  # shows comments in PRs
            eslint_flags: 'src --ext .js,.jsx,.ts,.tsx'

      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
    
      - name : Build Check
        run : npm run build
     
      - name: check for vulnerabilities
        run: npm audit
        
        



